### ISSUE TITLE
Idee: Als PlugIn in das YRewrite Scheme AddOn?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/parameter_rewrite#2]

**Comment by eaCe** [comment]
@skerbis kann man das in einem Scheme machen? Ich verstehe diese nicht wirklich. Sollte dem so sein würde ich das gerne als Trick aufnehmen

**Comment by skerbis** [comment]
Weiß nicht mehr. Ich close das Issue. Ist zu lange her.
