### ISSUE TITLE
PHP 7.2 Warning

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/parameter_rewrite#3]
`Warning: Use of undefined constant REQUEST_URI - assumed 'REQUEST_URI' (this will throw an Error in a future version of PHP) in /redaxo/src/addons/parameter_rewrite/lib/parameter_rewrite.php on line 46`

**Comment by iceman-fx** [comment]
Ich schließe mich diesem Fehler an.
Auch bei mir erscheint:
Notice: Use of undefined constant REQUEST_URI - assumed 'REQUEST_URI' in redaxo\src\addons\parameter_rewrite\lib\parameter_rewrite.php on line 46

**Comment by iceman-fx** [comment]
Lösung:
In Zeile 46 wurde die Abfrage der URI nicht PHP-konform aufgerufen.

Statt
`$path = $_SERVER[REQUEST_URI];`
sollte es so geschrieben werden:
`$path = $_SERVER['REQUEST_URI'];`

Anschließend war bei mir die Meldung weg.

**Comment by staabm** [comment]
gerne einen Pull Request erstellen
